language: node_js
sudo: false
node_js:
  - 8
env:
  - CXX=g++-4.8
services:
  - mongodb
  - redis-server
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.2-precise
    packages:
      - graphicsmagick
      - optipng
      - g++-4.8
      - mongodb-org-server
before_script:
  - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O /tmp/ffmpeg.tar.gz
  - wget http://www.rarlab.com/rar/rarlinux-x64-5.3.0.tar.gz -O /tmp/rar.tar.gz
  - mkdir bin
  - cd bin
  - tar -xvf /tmp/ffmpeg.tar.gz --strip 1 --no-anchored ffmpeg ffprobe
  - tar -xvf /tmp/rar.tar.gz --strip 1
  - cd ..
  - export PATH=$(pwd)/bin:$PATH
script:
  - deploy/ci/travis.sh
env:
  global:
    - secure: he13bEicdzpoLGeoj+xaU2kIkKsw1/m+Ejcm5YanhGicECrCWVvFOu0O7vGHPDDj3s/xnTgBhhUPzIS3SdcIVqfTS+nP+CJNtzOm4zOdPvmfbfCvuIukLmCLtADrrz2HUxO1en1vfpH1trkUP5gwdo4vAGli7hOD4MsncRYaYio=
    - BUILDER="Travis CI"
